Add fajita package to dependencies
Currently, this package fails on import due to missing fajita
dependency:

```
ModuleNotFoundError: No module named 'fajita'
```

This is solved by adding fajita to the `install_requires` list in
setup.py